### ISSUE TITLE
Error Cannot deserialize the current JSON object into type 'System.Int64'

### ISSUE THREAD

**Issue by rubenmch** [ovh/csharp-ovh#53]
I'm trying to use this library with .NET Core 3.1 but all the calls throw the following exception:

```
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ovh.Api.Client.CallAsync[T](String method, String path, String data, Boolean needAuth, Boolean isBatch, Nullable`1 timeout)
   at Ovh.Api.Client.ComputeTimeDelta()
   at Ovh.Api.Client.GetTimeDelta()
   at Ovh.Api.Client.SetHeaders(HttpRequestMessage msg, String method, String target, String data, Boolean needAuth, Boolean isBatch)
   at Ovh.Api.Client.CallAsync(String method, String path, String data, Boolean needAuth, Boolean isBatch, Nullable`1 timeout)
   at Ovh.Api.Client.CallAsync[T](String method, String path, String data, Boolean needAuth, Boolean isBatch, Nullable`1 timeout)
```

**Comment by rubenmch** [comment]
The `/auth/time` request is being made to `https://api.us.ovhcloud.com/1.0auth/time` which is what causes the exception. 

The following code in CallAsync removes the leading slash creating an incorrect uri.

```
            if (path.StartsWith("/"))
            {
                path = path.Substring(1);
            }
```

**Comment by Namaneo** [comment]
Hi,

Thanks for your investigation, indeed there's an issue with the US address. However, your change would potentially break every other regions.

After looking at the private constructor of `Client.cs`, the US address is missing a trailing slash. Could you try adding it instead of removing the `.Substring()`?

**Comment by rubenmch** [comment]
Hi @Namaneo, I created a new pull request adding the trailing slash.
